name: ksms
description: Koulis SMS

version: 1.0.0+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  ################### mine ###################
  flutter_sms_inbox: ^0.1.1+1
  # state management
  shared_preferences: ^0.5.12+4
  stacked: ^1.7.6
  stacked_hooks: ^0.1.3+2
  permission_handler: ^5.1.0+2
  # navigation
  auto_route: ^0.6.7
  stacked_services: ^0.6.6
  # inversion of control
  get_it: ^5.0.1
  injectable: ^1.0.4
  # widgets
  ################### mine end ###################

dev_dependencies:
  flutter_test:
    sdk: flutter

  ################### mine ###################
  flutter_launcher_icons: ^0.8.1
  build_runner:
  auto_route_generator: ^0.6.7
  injectable_generator: ^1.0.4
  ################### mine end ###################

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  image_path: "icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "icon_padded.png"
