name: ksms
description: Koulis SMS

version: 1.1.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  ################### mine ###################
  flutter_sms_inbox: ^0.1.1+1
  # state management
  shared_preferences: ^2.0.5
  stacked: ^1.7.6
  stacked_hooks: ^0.1.3+2
  permission_handler: ^6.1.1
  # navigation
  auto_route: ^1.0.2
  stacked_services: ^0.7.3
  # widgets
  ################### mine end ###################

dev_dependencies:
  flutter_test:
    sdk: flutter

  ################### mine ###################
  flutter_launcher_icons: ^0.9.0
  build_runner:
  stacked_generator:
  ################### mine end ###################

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  image_path: "icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "icon_padded.png"
